const ORDER_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  COOKING: 'COOKING',
  READY: 'READY',
  DELIVERING: 'DELIVERING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const ORDER_STATUS_LABELS = {
  [ORDER_STATUSES.PENDING]: 'Cho duyet',
  [ORDER_STATUSES.CONFIRMED]: 'Đã xác nhận',
  [ORDER_STATUSES.COOKING]: 'Đang nấu',
  [ORDER_STATUSES.READY]: 'Cho giao',
  [ORDER_STATUSES.DELIVERING]: 'Đang giao',
  [ORDER_STATUSES.COMPLETED]: 'Hoan thanh',
  [ORDER_STATUSES.CANCELLED]: 'Đã hủy'
};

const ORDER_STATUS_FLOW = [
  ORDER_STATUSES.PENDING,
  ORDER_STATUSES.CONFIRMED,
  ORDER_STATUSES.COOKING,
  ORDER_STATUSES.READY,
  ORDER_STATUSES.DELIVERING,
  ORDER_STATUSES.COMPLETED
];

const TERMINAL_ORDER_STATUSES = new Set([ORDER_STATUSES.COMPLETED, ORDER_STATUSES.CANCELLED]);

const isKnownOrderStatus = (status) => Object.prototype.hasOwnProperty.call(ORDER_STATUS_LABELS, status);

const getOrderStatusLabel = (status) => ORDER_STATUS_LABELS[status] || status;

module.exports = {
  ORDER_STATUSES,
  ORDER_STATUS_LABELS,
  ORDER_STATUS_FLOW,
  TERMINAL_ORDER_STATUSES,
  isKnownOrderStatus,
  getOrderStatusLabel
};
